#pragma once

#include "../SDK.h"

// Name: ARKSotF, Version: 178.8.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_786
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_786_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_785
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_785_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_784
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_784_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_783
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_783_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_782
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_782_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_781
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_781_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_780
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_780_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_779
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_779_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_778
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_778_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_777
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_777_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_776
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_776_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_775
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_775_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_774
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_774_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_773
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_773_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_772
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_772_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_771
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_771_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_770
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_770_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_769
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_769_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_768
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_768_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_767
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_767_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_766
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_766_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_765
struct UFPVBowWeaponAnimBP_NoRun_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_AnimGraphNode_TransitionResult_765_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.BlueprintUpdateAnimation
struct UFPVBowWeaponAnimBP_NoRun_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.AnimNotify_EnterIdle
struct UFPVBowWeaponAnimBP_NoRun_C_AnimNotify_EnterIdle_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.AnimNotify_EnterTargetIdle
struct UFPVBowWeaponAnimBP_NoRun_C_AnimNotify_EnterTargetIdle_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.AnimNotify_EndPullString
struct UFPVBowWeaponAnimBP_NoRun_C_AnimNotify_EndPullString_Params
{
};

// Function FPVBowWeaponAnimBP_NoRun.FPVBowWeaponAnimBP_NoRun_C.ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun
struct UFPVBowWeaponAnimBP_NoRun_C_ExecuteUbergraph_FPVBowWeaponAnimBP_NoRun_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
