#pragma once

#include "../SDK.h"

// Name: ARKSotF, Version: 178.8.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_562
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_562_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_561
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_561_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_560
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_560_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_559
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_559_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_558
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_558_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_557
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_557_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_556
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_556_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_555
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_555_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_554
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_554_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_553
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_553_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_552
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_552_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_551
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_551_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_550
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_550_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_138
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_138_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_76
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_76_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_432
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_432_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_139
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_139_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_433
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_433_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_140
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_140_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_135
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_135_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_75
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_75_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_426
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_426_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_136
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_136_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_427
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_SequencePlayer_427_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_137
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_BlendListByBool_137_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_LayeredBoneBlend_38
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_LayeredBoneBlend_38_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_549
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_549_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_548
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_TransitionResult_548_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_74
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_74_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_73
struct UFPVWeaponAnimBP_Base_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FPVWeaponAnimBP_Base_AnimGraphNode_ModifyBone_73_Params
{
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.BlueprintUpdateAnimation
struct UFPVWeaponAnimBP_Base_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function FPVWeaponAnimBP_Base.FPVWeaponAnimBP_Base_C.ExecuteUbergraph_FPVWeaponAnimBP_Base
struct UFPVWeaponAnimBP_Base_C_ExecuteUbergraph_FPVWeaponAnimBP_Base_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
